spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: kulvindra
    password:
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081